# Generated by Django 5.2.6 on 2025-09-23 11:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CookingMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="Способ приготовления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Способ приготовления",
                "verbose_name_plural": "Способы приготовления",
            },
        ),
        migrations.CreateModel(
            name="IngredientCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория ингредиентов",
                "verbose_name_plural": "Категории ингредиентов",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "default_unit",
                    models.CharField(
                        choices=[
                            ("g", "Граммы"),
                            ("kg", "Килограммы"),
                            ("ml", "Миллилитры"),
                            ("l", "Литры"),
                            ("pcs", "Штуки"),
                            ("tsp", "Чайные ложки"),
                            ("tbsp", "Столовые ложки"),
                            ("pinch", "Щепотка"),
                            ("to_taste", "По вкусу"),
                        ],
                        default="pcs",
                        max_length=50,
                        verbose_name="Единица по умолчанию",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.ingredientcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
            },
        ),
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Завтрак"),
                            ("lunch", "Обед"),
                            ("dinner", "Ужин"),
                            ("snack", "Перекус"),
                            ("supper", "Поздний ужин"),
                        ],
                        max_length=50,
                        verbose_name="Прием пищи",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "План питания",
                "verbose_name_plural": "Планы питания",
                "ordering": ["date", "meal_type"],
                "unique_together": {("user", "date", "meal_type")},
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название блюда"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "cooking_time",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Время приготовления (мин)"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Легко"),
                            ("medium", "Средне"),
                            ("hard", "Сложно"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Сложность",
                    ),
                ),
                ("instructions", models.TextField(verbose_name="Пошаговый рецепт")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="recipes/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "portions",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Количество порций"
                    ),
                ),
                (
                    "cooking_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.cookingmethod",
                        verbose_name="Способ приготовления",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Количество"
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="core.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ингредиент в рецепте",
                "verbose_name_plural": "Ингредиенты в рецептах",
            },
        ),
        migrations.CreateModel(
            name="RecipeMealPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "portions",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Количество порций"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to="core.mealplan",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.recipe",
                        verbose_name="Рецепт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецепт в плане питания",
                "verbose_name_plural": "Рецепты в плане питания",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Мой список покупок",
                        max_length=255,
                        verbose_name="Название списка",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Начало периода")),
                ("period_end", models.DateField(verbose_name="Конец периода")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("active", "Активный"),
                            ("completed", "Завершенный"),
                            ("archived", "В архиве"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершен"
                    ),
                ),
                (
                    "total_items",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего позиций"
                    ),
                ),
                (
                    "items_checked",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Куплено позиций"
                    ),
                ),
                (
                    "is_outdated",
                    models.BooleanField(default=False, verbose_name="Устарел"),
                ),
                (
                    "base_meal_plans",
                    models.ManyToManyField(
                        to="core.mealplan", verbose_name="Основано на планах питания"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Список покупок",
                "verbose_name_plural": "Списки покупок",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingListItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Количество"
                    ),
                ),
                (
                    "unit",
                    models.CharField(max_length=50, verbose_name="Единица измерения"),
                ),
                ("checked", models.BooleanField(default=False, verbose_name="Куплено")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Пользовательское название",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.ingredientcategory",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ingredient",
                        verbose_name="Ингредиент",
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.shoppinglist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент списка покупок",
                "verbose_name_plural": "Элементы списка покупок",
                "ordering": ["category__order", "order", "ingredient__name"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingListTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название шаблона"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Шаблон по умолчанию"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон списка покупок",
                "verbose_name_plural": "Шаблоны списков покупок",
            },
        ),
        migrations.CreateModel(
            name="TemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("unit", models.CharField(max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ingredient",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.shoppinglisttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
