# Generated by Django 5.2.6 on 2025-10-26 19:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tag_recipe_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_premium",
            field=models.BooleanField(default=False, verbose_name="Премиум рецепт"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="default_unit",
            field=models.CharField(
                choices=[
                    ("g", "гр."),
                    ("kg", "кг."),
                    ("ml", "мл."),
                    ("l", "л."),
                    ("pcs", "шт."),
                    ("tsp", "Чайные ложки"),
                    ("tbsp", "Столовые ложки"),
                    ("pinch", "Щепотка"),
                    ("to_taste", "По вкусу"),
                ],
                default="pcs",
                max_length=50,
                verbose_name="Единица по умолчанию",
            ),
        ),
        migrations.CreateModel(
            name="PremiumMealPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название меню"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Стоимость",
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(default=False, verbose_name="Бесплатное меню"),
                ),
                (
                    "duration_days",
                    models.IntegerField(
                        default=7, verbose_name="Продолжительность (дней)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="core.tag", verbose_name="Теги"
                    ),
                ),
            ],
            options={
                "verbose_name": "Премиум меню",
                "verbose_name_plural": "Премиум меню",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PremiumMealPlanRecipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("day_number", models.IntegerField(verbose_name="День меню")),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Завтрак"),
                            ("lunch", "Обед"),
                            ("dinner", "Ужин"),
                            ("snack", "Перекус"),
                            ("supper", "Поздний ужин"),
                        ],
                        max_length=50,
                        verbose_name="Прием пищи",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "premium_meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_recipes",
                        to="core.premiummealplan",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.recipe",
                        verbose_name="Рецепт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецепт в премиум меню",
                "verbose_name_plural": "Рецепты в премиум меню",
                "ordering": ["day_number", "meal_type", "order"],
                "unique_together": {
                    ("premium_meal_plan", "day_number", "meal_type", "order")
                },
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="available_in_premium_menus",
            field=models.ManyToManyField(
                blank=True,
                related_name="contained_recipes",
                through="core.PremiumMealPlanRecipe",
                to="core.premiummealplan",
                verbose_name="Доступен в премиум меню",
            ),
        ),
        migrations.CreateModel(
            name="UserPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purchase_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата покупки"
                    ),
                ),
                (
                    "price_paid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Оплаченная сумма",
                    ),
                ),
                (
                    "premium_meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.premiummealplan",
                        verbose_name="Премиум меню",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Покупка пользователя",
                "verbose_name_plural": "Покупки пользователей",
                "ordering": ["-purchase_date"],
                "unique_together": {("user", "premium_meal_plan")},
            },
        ),
    ]
