# Generated by Django 5.2.6 on 2025-11-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_recipe_is_premium_alter_ingredient_default_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpurchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("paid", "Оплачен"),
                    ("processing", "В обработке"),
                    ("cancelled", "Отказ"),
                ],
                default="processing",
                max_length=20,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
