# Generated by Django 5.2.6 on 2025-11-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_userpurchase_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpurchase",
            name="order_number",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                unique=True,
                verbose_name="Номер заказа для платежной системы",
            ),
        ),
    ]
