# Generated by Django 5.2.6 on 2025-11-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_userpurchase_order_number"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userpurchase",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="userpurchase",
            name="order_number",
            field=models.PositiveIntegerField(
                unique=True, verbose_name="Номер заказа для платежной системы"
            ),
        ),
    ]
